name = "Syn"
kinetic_model_file = "kinetic_model.toml"
reject_non_steady = false
priors_file = "priors.toml"
experiments_file = "experiments.toml"
likelihood = true
steady_state_threshold_abs = 1e-5

[cmdstanpy_config]
refresh = 1
iter_warmup = 500
iter_sampling = 500
chains = 2
save_warmup = true
seed = 1234
show_console=true

[ode_config]
abs_tol = 1e-5
rel_tol = 1e-5
max_num_steps = 1e6
timepoint = 1e3


