[[experiment]]
# The units are mol.s-1 (Based on GEM Flux)
id = "WT_GEM_Flux"
is_train = true
is_test = true
measurements = [
  {target_type = "flux", reaction = "DDPA", value = 1.0526819333333334e-09, error_scale = 2e-10},
  {target_type = "flux", reaction = "DHQS", value = 1.0526819333333334e-09, error_scale = 2e-10},
  {target_type = "flux", reaction = "DHQTi", value = 1.0526819333333334e-09, error_scale = 2e-10},
  {target_type = "flux", reaction = "SHK3Dr", value = 1.0526819333333334e-09, error_scale = 2e-10},
  {target_type = "flux", reaction = "SHKK", value = 1.0526819333333334e-09, error_scale = 2e-10},
  {target_type = "flux", reaction = "PSCVT", value = 1.0526819333333334e-09, error_scale = 2e-10},
  {target_type = "flux", reaction = "CHORS", value = 1.0526819333333334e-09, error_scale = 2e-10},
  {target_type = "flux", reaction = "CHORM", value = 8.546143666666667e-10, error_scale = 2e-10},
  {target_type = "flux", reaction = "PPNDH", value = 4.941118e-10, error_scale = 2e-10},
  {target_type = "flux", reaction = "PHETA1", value = 4.941118e-10, error_scale = 2e-10},
  {target_type = "flux", reaction = "PPND", value = 3.6050256666666667e-10, error_scale = 2e-10},
  {target_type = "flux", reaction = "TYRTA", value = 3.5910511e-10, error_scale = 2e-10},
]


[[experiment]]
# The units are molar
id = "WT_Proteomics"
is_train = true
is_test = true
measurements = [
  {target_type = "enzyme", enzyme = "DDPA1", value = 3.7457e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "DHQS1", value = 1.07915025e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "DHQTi1", value = 5.9531125e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "DHQTi2", value = 1.56579e-05, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "SHK3Dr1", value = 6.947995e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "SHKK1", value = 6.8647275e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PSCVT1", value = 2.6454965e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "CHORS1", value = 3.38060275e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "CHORM1", value = 1.29e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PPNDH1", value = 6.63e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PHETA11", value = 2.126355e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PHETA12", value = 6.48e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PHETA13", value = 1.65e-05, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PHETA14", value = 2.41e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PHETA15", value = 1.18e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PPND1", value = 2.89e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "TYRTA1", value = 2.126355e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "TYRTA2", value = 6.48e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "TYRTA3", value = 1.65e-05, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "TYRTA4", value = 2.41e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "TYRTA5", value = 1.18e-06, error_scale = 0.2},
]


[[experiment]]
# The units are molar
id = "OP2_Proteomics"
is_train = true
is_test = true
measurements = [
  {target_type = "enzyme", enzyme = "DDPA1", value = 2.220413e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "DHQS1", value = 8.490385e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "DHQTi1", value = 3.4589575e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "DHQTi2", value = 7.3509e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "SHK3Dr1", value = 2.262435e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "SHKK1", value = 3.207515e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PSCVT1", value = 1.26971625e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "CHORS1", value = 1.820399e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "CHORM1", value = 1.13e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PPNDH1", value = 5.92e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PHETA11", value = 1.28e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PHETA12", value = 2.83e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PHETA13", value = 7.57e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PHETA14", value = 4.85e-08, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PHETA15", value = 8.38e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PPND1", value = 2.30e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "TYRTA1", value = 1.28e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "TYRTA2", value = 2.83e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "TYRTA3", value = 7.57e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "TYRTA4", value = 4.85e-08, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "TYRTA5", value = 8.38e-07, error_scale = 0.2},
]


[[experiment]]
# The units are molar (M)
id = "OP4_Proteomics"
is_train = true
is_test = true
measurements = [
  {target_type = "enzyme", enzyme = "DDPA1", value = 1.85396175e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "DHQS1", value = 5.4469225e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "DHQTi1", value = 7.7469675e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "DHQTi2", value = 6.4469e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "SHK3Dr1", value = 2.56149e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "SHKK1", value = 2.4031725e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PSCVT1", value = 1.08014825e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "CHORS1", value = 1.7105225e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "CHORM1", value = 4.87e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PPNDH1", value = 3.13e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PHETA11", value = 1.25e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PHETA12", value = 2.08e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PHETA13", value = 5.50e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PHETA14", value = 6.89e-08, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PHETA15", value = 7.89e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "PPND1", value = 1.78e-07, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "TYRTA1", value = 1.25e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "TYRTA2", value = 2.08e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "TYRTA3", value = 5.50e-06, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "TYRTA4", value = 6.89e-08, error_scale = 0.2},
  {target_type = "enzyme", enzyme = "TYRTA5", value = 7.89e-07, error_scale = 0.2},
]


[[experiment]]
# The units are Molar (M)
id = "WT3_Metabolomics"
is_train = true
is_test = true
measurements = [
  {target_type = "mic", metabolite = "pep", compartment = "c", value = 2.876724, error_scale = 0.5},
  {target_type = "mic", metabolite = "nadp", compartment = "c", value = 0.810761, error_scale = 0.5},
  {target_type = "mic", metabolite = "adp", compartment = "c", value = 2.748757, error_scale = 0.5},
  {target_type = "mic", metabolite = "atp", compartment = "c", value = 1.701273, error_scale = 0.5},
  {target_type = "mic", metabolite = "akg", compartment = "c", value = 0.3271142, error_scale = 0.5},
  {target_type = "mic", metabolite = "glu", compartment = "c", value = 67.19126, error_scale = 0.5},
  {target_type = "mic", metabolite = "nad", compartment = "c", value = 1.227326, error_scale = 0.5},
  {target_type = "mic", metabolite = "tyr", compartment = "c", value = 94.89474, error_scale = 0.5}
]


[[experiment]]
# The units are Molar (M)
id = "WT5_Metabolomics"
is_train = true
is_test = true
measurements = [
  {target_type = "mic", metabolite = "pep", compartment = "c", value = 0.3866827, error_scale = 0.5},
  {target_type = "mic", metabolite = "nadp", compartment = "c", value = 0.3685238, error_scale = 0.5},
  {target_type = "mic", metabolite = "adp", compartment = "c", value = 1.527883, error_scale = 0.5},
  {target_type = "mic", metabolite = "atp", compartment = "c", value = 1.468323, error_scale = 0.5},
  {target_type = "mic", metabolite = "akg", compartment = "c", value = 0.2246436, error_scale = 0.5},
  {target_type = "mic", metabolite = "glu", compartment = "c", value = 64.43231, error_scale = 0.5},
  {target_type = "mic", metabolite = "nad", compartment = "c", value = 1.900289, error_scale = 0.5},
  {target_type = "mic", metabolite = "tyr", compartment = "c", value = 39.49223, error_scale = 0.5}
]


[[experiment]]
# The units are Molar (M)
id = "MT3_Metabolomics"
is_train = true
is_test = true
measurements = [
  {target_type = "mic", metabolite = "pep", compartment = "c", value = 0.2601158, error_scale = 0.5},
  {target_type = "mic", metabolite = "nadp", compartment = "c", value = 0.4660525, error_scale = 0.5},
  {target_type = "mic", metabolite = "adp", compartment = "c", value = 1.221581, error_scale = 0.5},
  {target_type = "mic", metabolite = "atp", compartment = "c", value = 2.062672, error_scale = 0.5},
  {target_type = "mic", metabolite = "akg", compartment = "c", value = 0.01034102, error_scale = 0.5},
  {target_type = "mic", metabolite = "glu", compartment = "c", value = 34.29985, error_scale = 0.5},
  {target_type = "mic", metabolite = "nad", compartment = "c", value = 1.072991, error_scale = 0.5},
  {target_type = "mic", metabolite = "tyr", compartment = "c", value = 3684.293, error_scale = 0.5}
]


[[experiment]]
# The units are Molar (M)
id = "MT5_Metabolomics"
is_train = true
is_test = true
measurements = [
  {target_type = "mic", metabolite = "pep", compartment = "c", value = 0.1260061, error_scale = 0.5},
  {target_type = "mic", metabolite = "nadp", compartment = "c", value = 0.3217922, error_scale = 0.5},
  {target_type = "mic", metabolite = "adp", compartment = "c", value = 1.053493, error_scale = 0.5},
  {target_type = "mic", metabolite = "atp", compartment = "c", value = 1.199599, error_scale = 0.5},
  {target_type = "mic", metabolite = "akg", compartment = "c", value = 0.5961815, error_scale = 0.5},
  {target_type = "mic", metabolite = "glu", compartment = "c", value = 35.68264, error_scale = 0.5},
  {target_type = "mic", metabolite = "nad", compartment = "c", value = 1.147905, error_scale = 0.5},
  {target_type = "mic", metabolite = "tyr", compartment = "c", value = 4025.459, error_scale = 0.5}
]