[[experiment]]
id = "condition1"
is_train = true
is_test = true
measurements = [
  {target_type = "flux", reaction = "DDPA", value = 1.0526819333333334e-09, error_scale = 0.2},
  {target_type = "flux", reaction = "DHQS", value = 1.0526819333333334e-09, error_scale = 0.2},
  {target_type = "flux", reaction = "DHQTi", value = 1.0526819333333334e-09, error_scale = 0.2},
  {target_type = "flux", reaction = "SHK3Dr", value = 1.0526819333333334e-09, error_scale = 0.2},
  {target_type = "flux", reaction = "SHKK", value = 1.0526819333333334e-09, error_scale = 0.2},
  {target_type = "flux", reaction = "PSCVT", value = 1.0526819333333334e-09, error_scale = 0.2},
  {target_type = "flux", reaction = "CHORS", value = 1.0526819333333334e-09, error_scale = 0.2},
  {target_type = "flux", reaction = "CHORM", value = 8.546143666666667e-10, error_scale = 0.2},
  {target_type = "flux", reaction = "PPNDH", value = 4.941118e-10, error_scale = 0.2},
  {target_type = "flux", reaction = "PHETA1", value = 4.941118e-10, error_scale = 0.2},
  {target_type = "flux", reaction = "PPND", value = 3.6050256666666667e-10, error_scale = 0.2},
  {target_type = "flux", reaction = "TYRTA", value = 3.5910511e-10, error_scale = 0.2},
]

