#####Kinetic model #####

compartment = [
  {id = 'c', name = 'cytosol', volume = 1},
  ]

  metabolite = [
  {id = "pep", name = "Phosphoenolpyruvate"},
  {id = "e4p", name = "Erythrose 4-phosphate"},
  {id = "pi", name = "Phosphate"},
  {id = "2dda7p", name = "2-dehydro-3-deoxyarabino-heptulosonate 7-phosphate"},
  {id = "3dhq", name = "3-dehydroquinate"},
  {id = "3dhsk", name = "3-dehydroshikimate"},
  {id = "skm", name = "Shikimate"},
  {id = "nadp", name = "Nicotinamide adenine dinucleotide phosphate"},
  {id = "nadph", name = "Nicotinamide adenine dinucleotide phosphate - reduced"},
  {id = "atp", name = "ATP C10H12N5O13P3"},
  {id = "adp", name = "ADP C10H12N5O10P2"},
  {id = "skm5p", name = "Shikimate 5-phosphate"},
  {id = "3psme", name = "5-O-(1-Carboxyvinyl)-3-phosphoshikimate"},
  {id = "chor", name = "Chorismate"},
  {id = "pphn", name = "Prephenate"},
  {id = "co2", name = "CO2"},
  {id = "phpyr", name = "Phenylpyruvate"},
  {id = "akg", name = "2-Oxoglutarate"},
  {id = "phe", name = "L-phenylalanine"},
  {id = "glu", name = "L-Glutamate"},
  {id = "nad", name = "Nicotinamide adenine dinucleotide"},
  {id = "nadh", name = "Nicotinamide adenine dinucleotide - reduced"},
  {id = "34hpp", name = "3-(4-Hydroxyphenyl)pyruvate"},
  {id = "tyr", name = "L-Tyrosine"},
]


metabolite_in_compartment = [
  {metabolite_id = "pep", compartment_id = "c", balanced = false},
  {metabolite_id = "e4p", compartment_id = "c", balanced = false},
  {metabolite_id = "pi", compartment_id = "c", balanced = false},
  {metabolite_id = "2dda7p", compartment_id = "c", balanced = true},
  {metabolite_id = "3dhq", compartment_id = "c", balanced = true},
  {metabolite_id = "3dhsk", compartment_id = "c", balanced = true},
  {metabolite_id = "skm", compartment_id = "c", balanced = true},
  {metabolite_id = "nadp", compartment_id = "c", balanced = false},
  {metabolite_id = "nadph", compartment_id = "c", balanced = false},
  {metabolite_id = "atp", compartment_id = "c", balanced = false},
  {metabolite_id = "adp", compartment_id = "c", balanced = false},
  {metabolite_id = "skm5p", compartment_id = "c", balanced = true},
  {metabolite_id = "3psme", compartment_id = "c", balanced = true},
  {metabolite_id = "chor", compartment_id = "c", balanced = true},
  {metabolite_id = "pphn", compartment_id = "c", balanced = true},
  {metabolite_id = "co2", compartment_id = "c", balanced = false},
  {metabolite_id = "phpyr", compartment_id = "c", balanced = true},
  {metabolite_id = "akg", compartment_id = "c", balanced = false},
  {metabolite_id = "phe", compartment_id = "c", balanced = false},
  {metabolite_id = "glu", compartment_id = "c", balanced = false},
  {metabolite_id = "nad", compartment_id = "c", balanced = false},
  {metabolite_id = "nadh", compartment_id = "c", balanced = false},
  {metabolite_id = "34hpp", compartment_id = "c", balanced = true},
  {metabolite_id = "tyr", compartment_id = "c", balanced = false},
]

enzyme = [
  {id = "DDPA1", name = "3-deoxy-7-phosphoheptulonate synthase 1", subunits = 1},
  {id = "DHQS1", name = "3-dehydroquinate synthase 1", subunits = 1},
  {id = "DHQTi1", name = "3-dehydroquinate dehydratase 1", subunits = 1},
  {id = "DHQTi2", name = "3-dehydroquinate dehydratase 2", subunits = 1},
  {id = "SHK3Dr1", name = "Shikimate dehydrogenase 1", subunits = 1},
  {id = "SHKK1", name = "Shikimate kinase 1", subunits = 1},
  {id = "PSCVT1", name = "3-phosphoshikimate 1-carboxyvinyltransferase 1", subunits = 1},
  {id = "CHORS1", name = "Chorismate synthase 1", subunits = 1},
  {id = "CHORM1", name = "Chorismate mutase 1", subunits = 1},
  {id = "PPNDH1", name = "Prephenate dehydratase 1", subunits = 1},
  {id = "PHETA11", name = "Phenylalanine transaminase 1", subunits = 1},
  {id = "PHETA12", name = "Phenylalanine transaminase 2", subunits = 1},
  {id = "PHETA13", name = "Phenylalanine transaminase 3", subunits = 1},
  {id = "PPND1", name = "Prephenate dehydrogenase 1", subunits = 1},
  {id = "TYRTA1", name = "Tyrosine transaminase 1", subunits = 1},
  {id = "TYRTA2", name = "Tyrosine transaminase 2", subunits = 1},
  {id = "TYRTA3", name = "Tyrosine transaminase 3", subunits = 1},
]


enzyme_reaction = [
  {enzyme_id = "DDPA1", reaction_id = "DDPA"},
  {enzyme_id = "DHQS1", reaction_id = "DHQS"},
  {enzyme_id = "DHQTi1", reaction_id = "DHQTi"},
  {enzyme_id = "DHQTi2", reaction_id = "DHQTi"},
  {enzyme_id = "SHK3Dr1", reaction_id = "SHK3Dr"},
  {enzyme_id = "SHKK1", reaction_id = "SHKK"},
  {enzyme_id = "PSCVT1", reaction_id = "PSCVT"},
  {enzyme_id = "CHORS1", reaction_id = "CHORS"},
  {enzyme_id = "CHORM1", reaction_id = "CHORM"},
  {enzyme_id = "PPNDH1", reaction_id = "PPNDH"},
  {enzyme_id = "PHETA11", reaction_id = "PHETA1"},
  {enzyme_id = "PHETA12", reaction_id = "PHETA1"},
  {enzyme_id = "PHETA13", reaction_id = "PHETA1"},
  {enzyme_id = "PPND1", reaction_id = "PPND"},
  {enzyme_id = "TYRTA1", reaction_id = "TYRTA"},
  {enzyme_id = "TYRTA2", reaction_id = "TYRTA"},
  {enzyme_id = "TYRTA3", reaction_id = "TYRTA"},
]


[[reaction]]
id = "DDPA"
name = "3-deoxy-7-phosphoheptulonate synthase"
water_stoichiometry = -1
stoichiometry = {pep_c= -1, e4p_c= -1, 2dda7p_c= 1, pi_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "DHQS"
name = "3-dehydroquinate synthase"
stoichiometry = {2dda7p_c= -1, 3dhq_c= 1, pi_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "DHQTi"
name = "3-dehydroquinate dehydratase"
water_stoichiometry = 1
stoichiometry = {3dhq_c= -1, 3dhsk_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "SHK3Dr"
name = "Shikimate dehydrogenase"
stoichiometry = {3dhsk_c= -1, nadph_c= -1, skm_c= 1, nadp_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "SHKK"
name = "Shikimate kinase"
stoichiometry = {skm_c= -1, atp_c= -1, skm5p_c= 1, adp_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "PSCVT"
name = "3-phosphoshikimate 1-carboxyvinyltransferase"
stoichiometry ={skm5p_c= -1, pep_c= -1, 3psme_c= 1, pi_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "CHORS"
name = "Chorismate synthase"
stoichiometry = {3psme_c= -1, chor_c= 1, pi_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "CHORM"
name = "Chorismate mutase"
stoichiometry = {chor_c= -1, pphn_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "PPNDH"
name = "Prephenate dehydratase"
water_stoichiometry = 1
stoichiometry = {pphn_c= -1, co2_c= 1, phpyr_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "PHETA1"
name = "Phenylalanine transaminase"
stoichiometry = {akg_c= 1, phe_c= 1, glu_c= -1, phpyr_c= -1}
mechanism = "reversible_michaelis_menten"


[[reaction]]
id = "PPND"
name = "Prephenate dehydrogenase"
stoichiometry = {nad_c= -1, pphn_c= -1, nadh_c= 1, 34hpp_c= 1, co2_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "TYRTA"
name = "Tyrosine transaminase"
stoichiometry = {akg_c= 1, tyr_c= 1, glu_c= -1, 34hpp_c= -1}
mechanism = "reversible_michaelis_menten"




