#####Kinetic model #####

compartment = [
  {id = 'c', name = 'cytosol', volume = 1},
  {id = 'e', name = 'external', volume = 1},
  ]


metabolite = [
  {id = "pep", name = "Phosphoenolpyruvate"},
  {id = "e4p", name = "Erythrose 4-phosphate"},
  {id = "pi", name = "Phosphate"},
  {id = "2dda7p", name = "2-dehydro-3-deoxyarabino-heptulosonate 7-phosphate"},
  {id = "3dhq", name = "3-dehydroquinate"},
  {id = "3dhsk", name = "3-dehydroshikimate"},
  {id = "skm", name = "Shikimate"},
  {id = "nadp", name = "Nicotinamide adenine dinucleotide phosphate"},
  {id = "nadph", name = "Nicotinamide adenine dinucleotide phosphate - reduced"},
  {id = "atp", name = "ATP C10H12N5O13P3"},
  {id = "adp", name = "ADP C10H12N5O10P2"},
  {id = "skm5p", name = "Shikimate 5-phosphate"},
  {id = "3psme", name = "5-O-(1-Carboxyvinyl)-3-phosphoshikimate"},
  {id = "chor", name = "Chorismate"},
  {id = "pphn", name = "Prephenate"},
  {id = "co2", name = "CO2"},
  {id = "phpyr", name = "Phenylpyruvate"},
  {id = "akg", name = "2-Oxoglutarate"},
  {id = "phe", name = "L-phenylalanine"},
  {id = "glu", name = "L-Glutamate"},
  {id = "nad", name = "Nicotinamide adenine dinucleotide"},
  {id = "nadh", name = "Nicotinamide adenine dinucleotide - reduced"},
  {id = "34hpp", name = "3-(4-Hydroxyphenyl)pyruvate"},
  {id = "tyr", name = "L-Tyrosine"},
]


enzyme = [
  {id = "DDPA", name = "3-deoxy-7-phosphoheptulonate synthase"},
  {id = "DHQS", name = "3-dehydroquinate synthase"},
  {id = "DHQTi", name = "3-dehydroquinate dehydratase"},
  {id = "SHK3Dr", name = "Shikimate dehydrogenase"},
  {id = "SHKK", name = "Shikimate kinase"},
  {id = "PSCVT", name = "3-phosphoshikimate 1-carboxyvinyltransferase"},
  {id = "CHORS", name = "Chorismate synthase"},
  {id = "CHORM", name = "Chorismate mutase"},
  {id = "PPNDH", name = "Prephenate dehydratase"},
  {id = "PHETA1", name = "Phenylalanine transaminase"},
  {id = "PPND", name = "Prephenate dehydrogenase"},
  {id = "TYRTA", name = "Tyrosine transaminase"},
  {id = "eTYRTA", name = "Tyrosine Exchange"},
  {id = "ePHETA1", name = "Phenylalanine Exchange"},
]


metabolite_in_compartment = [
  {metabolite_id = "pep", compartment_id = "c", balanced = false},
  {metabolite_id = "e4p", compartment_id = "c", balanced = false},
  {metabolite_id = "pi", compartment_id = "c", balanced = false},
  {metabolite_id = "2dda7p", compartment_id = "c", balanced = true},
  {metabolite_id = "3dhq", compartment_id = "c", balanced = true},
  {metabolite_id = "3dhsk", compartment_id = "c", balanced = true},
  {metabolite_id = "skm", compartment_id = "c", balanced = true},
  {metabolite_id = "nadp", compartment_id = "c", balanced = false},
  {metabolite_id = "nadph", compartment_id = "c", balanced = false},
  {metabolite_id = "atp", compartment_id = "c", balanced = false},
  {metabolite_id = "adp", compartment_id = "c", balanced = false},
  {metabolite_id = "skm5p", compartment_id = "c", balanced = true},
  {metabolite_id = "3psme", compartment_id = "c", balanced = true},
  {metabolite_id = "chor", compartment_id = "c", balanced = true},
  {metabolite_id = "pphn", compartment_id = "c", balanced = true},
  {metabolite_id = "co2", compartment_id = "c", balanced = false},
  {metabolite_id = "phpyr", compartment_id = "c", balanced = true},
  {metabolite_id = "akg", compartment_id = "c", balanced = false},
  {metabolite_id = "phe", compartment_id = "c", balanced = true},
  {metabolite_id = "glu", compartment_id = "c", balanced = false},
  {metabolite_id = "nad", compartment_id = "c", balanced = false},
  {metabolite_id = "nadh", compartment_id = "c", balanced = false},
  {metabolite_id = "34hpp", compartment_id = "c", balanced = true},
  {metabolite_id = "tyr", compartment_id = "c", balanced = true},
  {metabolite_id = "tyr", compartment_id = "e", balanced = false},
  {metabolite_id = "phe", compartment_id = "e", balanced = false},
]


enzyme_reaction = [
  {enzyme_id = "DDPA", reaction_id = "DDPA"},
  {enzyme_id = "DHQS", reaction_id = "DHQS"},
  {enzyme_id = "DHQTi", reaction_id = "DHQTi"},
  {enzyme_id = "SHK3Dr", reaction_id = "SHK3Dr"},
  {enzyme_id = "SHKK", reaction_id = "SHKK"},
  {enzyme_id = "PSCVT", reaction_id = "PSCVT"},
  {enzyme_id = "CHORS", reaction_id = "CHORS"},
  {enzyme_id = "CHORM", reaction_id = "CHORM"},
  {enzyme_id = "PPNDH", reaction_id = "PPNDH"},
  {enzyme_id = "PHETA1", reaction_id = "PHETA1"},
  {enzyme_id = "PPND", reaction_id = "PPND"},
  {enzyme_id = "TYRTA", reaction_id = "TYRTA"},
  {enzyme_id = "eTYRTA", reaction_id = "eTYRTA"},
  {enzyme_id = "ePHETA1", reaction_id = "ePHETA1"},
]


[[reaction]]
id = "DDPA"
name = "3-deoxy-7-phosphoheptulonate synthase"
water_stoichiometry = -1
stoichiometry = {pep_c= -1, e4p_c= -1, 2dda7p_c= 1, pi_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "DHQS"
name = "3-dehydroquinate synthase"
stoichiometry = {2dda7p_c= -1, 3dhq_c= 1, pi_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "DHQTi"
name = "3-dehydroquinate dehydratase"
water_stoichiometry = 1
stoichiometry = {3dhq_c= -1, 3dhsk_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "SHK3Dr"
name = "Shikimate dehydrogenase"
stoichiometry = {3dhsk_c= -1, nadph_c= -1, skm_c= 1, nadp_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "SHKK"
name = "Shikimate kinase"
stoichiometry = {skm_c= -1, atp_c= -1, skm5p_c= 1, adp_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "PSCVT"
name = "3-phosphoshikimate 1-carboxyvinyltransferase"
stoichiometry ={skm5p_c= -1, pep_c= -1, 3psme_c= 1, pi_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "CHORS"
name = "Chorismate synthase"
stoichiometry = {3psme_c= -1, chor_c= 1, pi_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "CHORM"
name = "Chorismate mutase"
stoichiometry = {chor_c= -1, pphn_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "PPNDH"
name = "Prephenate dehydratase"
water_stoichiometry = 1
stoichiometry = {pphn_c= -1, co2_c= 1, phpyr_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "PHETA1"
name = "Phenylalanine transaminase"
stoichiometry = {akg_c= 1, phe_c= 1, glu_c= -1, phpyr_c= -1}
mechanism = "reversible_michaelis_menten"


[[reaction]]
id = "PPND"
name = "Prephenate dehydrogenase"
stoichiometry = {nad_c= -1, pphn_c= -1, nadh_c= 1, 34hpp_c= 1, co2_c= 1}
mechanism = "irreversible_michaelis_menten"


[[reaction]]
id = "TYRTA"
name = "Tyrosine transaminase"
stoichiometry = {akg_c= 1, tyr_c= 1, glu_c= -1, 34hpp_c= -1}
mechanism = "reversible_michaelis_menten"


[[reaction]]
id = "eTYRTA"
name = "Tyrosine Exchange"
stoichiometry = {tyr_c=-1, tyr_e=1}
mechanism = "reversible_michaelis_menten"


[[reaction]]
id = "ePHETA1"
name = "Phenylalanine Exchange"
stoichiometry = {phe_c=-1, phe_e=1}
mechanism = "reversible_michaelis_menten"


